version: '3.9'
services:
  host-server:
    build: ./host/
    ports:
    - 8080:80
  s1-server:
    build: ./service1/
    ports:
    - 8081:80
  s2-server:
    build: ./service2/
    ports:
    - 8082:80